# REMEMBER TO EDIT THIS BEFORE DEPLOY!!!

# the path to your blog's icon:
favicon: /theme-img/favicon.ico

# the path to manifest.json
manifest: /manifest.json

# show excerpt on post list
show_excerpt: false

# navigation config
nav:
  # the title displays in the upper left corner which won't change
  title: savagezen
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Podcast: /categories/Podcast
    Research: /categories/Research
    Essays: /categories/Essays
    Sponsors: /support
    About: /about
    # these will be automatically be an icon
    Instagram: https://instagram.com/savagezen
    Twitter: https://twitter.com/carnivorebjj
    GitHub: https://github.com/savagezen
    PayPal: https://paypal.me/savagezen

# footer items
footer:
  # the title
  Blog:
    # the items after the title, display as links
    Research: /research
    Essays: /essays
    Archives: https://github.com/savagezen/savagezen.github.io/tree/master/source/_archive
    Subscribe to RSS: /atom.xml
  # also the title
  Podcast:
    # the items
    Browse All Episodes: /podcast
    Listen on Apple Podcasts: https://podcasts.apple.com/us/podcast/kombat-kitchen/id1547452233?uo=4
    Listen on Google Podcasts: https://podcasts.google.com/feed/aHR0cDovL3Jzcy5jYXN0Ym94LmZtL2V2ZXJlc3QvZDZkZTFjMmFjZmY1NDhhNzk0YzFiOGU3ZTdiN2Q5YzgueG1s
    Listen on Spotify: https://open.spotify.com/show/5cpMxrfTHovAzz4qNf5y0r
    Listen on Anchor: https://anchor.fm/kombatkitchen
    Listen on Castbox: https://castbox.fm/channel/id2937016?country=us
  # the title
  Me:
    # items
    About: /about
    Support this Site: /support
#    Instagram: https://instagram.com/savagezen
#    Twitter: https://twitter.com/carnivorebjj
#    GitHub: https://github.com/savagezen
#    PayPal: https://paypal.me/savagezen

# the license your posts under
license: CC BY-NC 4.0
# the link of your license
license_link: https://creativecommons.org/licenses/by-nc/4.0

# REMEMBER TO EDIT THIS BEFORE DEPLOY!!!
